use anchor_lang::prelude::*;
use mpl_bubblegum::programs::bubblegum::Bubblegum;
use spl_account_compression::programs::{spl_account_compression::SplAccountCompression, spl_noop::SplNoop};

// Replace with your deployed program ID generated by `anchor keys list`
// e.g. declare_id!("xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx");
declare_id!("11111111111111111111111111111111");

#[program]
pub mod credify_program {
	use super::*;

	pub fn create_tree(
		_ctx: Context<CreateTree>,
		_max_depth: u32,
		_max_buffer_size: u32,
	) -> Result<()> {
		Ok(())
	}

	pub fn transfer_credential<'info>(
		_ctx: Context<'_, '_, '_, 'info, TransferCredential<'info>>,
		_root: [u8; 32],
		_data_hash: [u8; 32],
		_creator_hash: [u8; 32],
		_nonce: u64,
		_index: u32,
	) -> Result<()> {
		Ok(())
	}

	pub fn burn_credential<'info>(
		_ctx: Context<'_, '_, '_, 'info, BurnCredential<'info>>,
		_root: [u8; 32],
		_data_hash: [u8; 32],
		_creator_hash: [u8; 32],
		_nonce: u64,
		_index: u32,
	) -> Result<()> {
		Ok(())
	}
}

#[derive(Accounts)]
#[instruction(max_depth: u32, max_buffer_size: u32)]
pub struct CreateTree<'info> {
	#[account(mut)]
	pub payer: Signer<'info>,

	#[account(
		seeds = [b"authority"],
		bump
	)]
	pub tree_authority: SystemAccount<'info>,

	#[account(mut)]
	/// CHECK: Merkle tree account to be allocated/initialized via CPI
	pub merkle_tree: UncheckedAccount<'info>,

	// Required Programs
	pub bubblegum_program: Program<'info, Bubblegum>,
	pub compression_program: Program<'info, SplAccountCompression>,
	pub log_wrapper: Program<'info, SplNoop>,
	pub system_program: Program<'info, System>,
}

#[derive(Accounts)]
pub struct TransferCredential<'info> {
	#[account(
		seeds = [b"authority"],
		bump
	)]
	pub tree_authority: SystemAccount<'info>,

	/// CHECK: The owner of the cNFT (must sign)
	#[account(signer)]
	pub leaf_owner: UncheckedAccount<'info>,
	/// CHECK: The new owner of the cNFT
	pub leaf_delegate: UncheckedAccount<'info>,
	/// CHECK: The Merkle tree
	#[account(mut)]
	pub merkle_tree: UncheckedAccount<'info>,

	// Required Programs
	pub log_wrapper: Program<'info, SplNoop>,
	pub compression_program: Program<'info, SplAccountCompression>,
	pub bubblegum_program: Program<'info, Bubblegum>,
	pub system_program: Program<'info, System>,
}

#[derive(Accounts)]
pub struct BurnCredential<'info> {
	#[account(
		seeds = [b"authority"],
		bump
	)]
	pub tree_authority: SystemAccount<'info>,

	/// CHECK: The owner of the cNFT (must sign)
	#[account(signer)]
	pub leaf_owner: UncheckedAccount<'info>,
	/// CHECK: The Merkle tree
	#[account(mut)]
	pub merkle_tree: UncheckedAccount<'info>,

	// Required Programs
	pub log_wrapper: Program<'info, SplNoop>,
	pub compression_program: Program<'info, SplAccountCompression>,
	pub bubblegum_program: Program<'info, Bubblegum>,
	pub system_program: Program<'info, System>,
}

